### ISSUE TITLE
USER STORY: Learn about site

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#1]
As a **visiting user** I can **learn what the site is about** so that **I can decide whether to sign up to the site**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The first thing a user should see on entering the website is an image relevant to the topic and a tagline explaining exactly what the website is for
 *  Acceptance Criteria 2: There should be a Learn More button here, which will link to more detailed information
 *  Acceptance Criteria 3: Below the image there should be a section briefly explaining the purpose of the website/the benefits for the user

# Tasks
 - [x] Source the image to be used and re-size if needed
 - [x] Create the block content in index.html for landing image, tagline and button, and the brief explanatory section
 - [x] Style the content
 - [x] Manually test to ensure the content is responsive and any links work (view already tested in #2

**Comment by Fiona-T** [comment]
Tasks completed. Acceptance criteria met. Links (My Jobs and My Pensions) to be re-tested once header updated. Closed.
