### ISSUE TITLE
USER STORY: Delete a job

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#10]
As a **registered user** I can **delete a job** so that **I can remove it from my records if I added it in error**

# Acceptance Criteria
 *  Acceptance Criteria 1:  User can click on the Delete button on the jobs list, this brings up a confirmation page asking the user to confirm the deletion
 *  Acceptance Criteria 2:  There is a cancel button (to go back to my-jobs list) and a button to confirm deletion
 *  Acceptance Criteria 3: The job no longer exists in the job list after pressing the delete button
 * Acceptance Criteria 4: After pressing the delete button, the user is redirected to the my jobs page

# Tasks
 - [x] Create the view logic
 - [x] Create the template to display delete message to user
 - [x] Update the styles to be applied, if necessary (if any additional styles needed)
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed, deletion done via modal. Acceptance criteria met. Ran tests and did manual tests as well. Closed
