### ISSUE TITLE
USER STORY: Add pension

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#11]
As a **registered user** I can **record the details of a pension** so that **I can have the pension recorded on my account**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A registered user can go to the My Pensions page, click Add a Pension and a form is displayed for them to complete
 *  Acceptance Criteria 2: The form contains fields for Employment(dropdown list from user's previously created jobs), pension scheme name, policy no., scheme no., type of pension, salary, PAO, 20% director, pension provider, value, file upload field, additional notes.
 *  Acceptance Criteria 3: All fields on the form are mandatory except member number, file upload and additional notes
 * Acceptance Criteria 4: After adding the pension details, the user can see these details in the My Pensions page (this depends on #12 

# Tasks
 - [x] Create the Pension model, make and run migrations
 - [x] Update the project urls file with path for pensions app urls
 - [x] Add the add pension page url to pensions app url file
 - [x] Need the my pensions view to be created, as the add job button sits here. Depends on #12 
 - [x] Create the add pension template
 - [x] Create the add pension form
 - [x] Create the view for displaying the add pension form
 - [x] Create the view for posting the completed add pension form
 - [x] Style the page (css/bootstrap classes)
 - [x] Test the add pension view
 - [x] Test the Pension model
 - [x] Test the add pension form

**Comment by Fiona-T** [comment]
All tasks completed and acceptance criteria met. Automated and manual testing completed. Closed.
