### ISSUE TITLE
USER STORY: View pensions

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#12]
As a **registered user** I can ** view the pensions I have added** so that **I can see all my pension details in one place**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is logged in and on the My Pensions page, all pensions added by that user are listed here
 *  Acceptance Criteria 2: The pensions added to date are shown in a section called Your Pensions, with summary details shown
 *  Acceptance Criteria 3: Each pension has the Scheme name, employer name and value shown, and buttons to View the full details, Edit, and Delete the pension

# Tasks
 - [x] create the my-pensions.html template
 - [x] add the url to the pensions urls.py file
 - [x] create the MyPensions view to display the pensions retrieved from the database
 - [x] style the template (CSS/bootstrap classes)
 - [x] Test the view
 - [x] add the url for my-pensions to the nav header in base.html and the links in index.html and check for any other links on other pages

**Comment by Fiona-T** [comment]
This was completed on Thursday 16th, forgot to close off. All tasks completed and acceptance criteria met, automated and manual testing completed. Closed.
