### ISSUE TITLE
USER STORY: Edit pension details

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#13]
As a **registered user** I can **edit a pension I previously added** so that **I can correct or update the previously recorded information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  User can click on the Edit button on the pensions list, and this brings up a form to edit the details
 *  Acceptance Criteria 2: The existing details of the pension are pre-populated on the form so user just needs to update the fields that are changing
 *  Acceptance Criteria 3: The form contains the same fields as the Add Pension form, along with a confirmation button to Confirm, or a cancel button to go back
 * Acceptance Criteria 4: After submitting the form, the user is redirected to the my pensions page
 * Acceptance Criteria 5: The pension in the pensions list now shows the amended details

# Tasks
 - [x] Create the edit-pension template
 - [x] Create the view logic to render the template
 - [x] Update the urls file with the url
 - [x] Update the link on my-pensions with the new edit-pension page url
 - [x] Update CSS as needed (style.css / Bootstrap classes)
 - [x] Test the view (form already tested in #11 )

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, automated tests completed. Closed.
