### ISSUE TITLE
USER STORY: Delete a pension

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#14]
As a **registered user** I can **delete a pension I previously added** so that **I can remove it from my records if I added it in error**

# Acceptance Criteria
 *  Acceptance Criteria 1:  User can click on the Delete button on the pensions list, this brings up a confirmation page asking the user to confirm the deletion
 *  Acceptance Criteria 2: There is a cancel button (to go back to my-pensions list) and a button to confirm deletion
 *  Acceptance Criteria 3: The pension no longer exists in the pension list after pressing the delete button
 * Acceptance Criteria 4: After pressing the delete button, the user is redirected to the my pensions page

# Tasks
 - [x] add the modal html code to the my-pensions page
 - [x] Create the view to handle the deletion
 - [x] Update the styles as needed (style.css / Bootstrap classes)
 - [x] Test the view

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, automated and manual testing completed. Closed.
