### ISSUE TITLE
USER STORY: Access external resources

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#15]
As a **site user** I can **access external resources relating to pensions** so that **I can find out more information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The links are in the footer on each page
 *  Acceptance Criteria 2:  Links to be included are: The Pensions Authority (https://www.pensionsauthority.ie/en/), Revenue Commissioners (https://www.revenue.ie/en/jobs-and-pensions/pensions/index.aspx) and Citizens Information (https://www.citizensinformation.ie/en/money_and_tax/personal_finance/pensions/)
 *  Acceptance Criteria 3: The links open in a new window

# Tasks
 - [x] Create the footer in base.html template and add CSS for footer design
 - [x] Need index.html being created as part of #2 to view the footer on the frontend
 - [x] Test manually - links work and open in a new window. Unit test on the view will be done as part of #2

**Comment by Fiona-T** [comment]
All tasks completed and Acceptance Criteria fulfilled. Closed.
