### ISSUE TITLE
USER STORY: Find the social media links

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#16]
As a **site user** I can **find the PensionPal social media accounts** so that **I can follow them on social media to keep up to date**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The social media icons are in the footer on each page
 *  Acceptance Criteria 2: The links open in a new window
 *  Acceptance Criteria 3: The links/icons are for LinkedIn, Instagram, Facebook and Twitter

# Tasks
 - [x] Update the footer in base.html to include the social media icons, depends on footer being created by #15 
 - [x] Style the footer (CSS)
 - [x] Manually test to ensure links open correctly and in new window, view testing of index.html done in #2

**Comment by Fiona-T** [comment]
Task completed, Acceptance Criteria fulfilled. Closed.
