### ISSUE TITLE
USER STORY: Add pension provider to pension providers list

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#17]
As a **website owner/admin** I can **add pension providers to a table in the admin panel** so that **users can select the pension provider when adding or editing a pension in My Pensions page**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When logged into the admin panel, the user can add a new Pension Provider
 *  Acceptance Criteria 2: The details the admin user can record for the pension provider is: name, website url and status (active or not active)
 *  Acceptance Criteria 3: Only the admin user can access this admin panel and Pension Provider table

# Tasks
 - [x] Create the 'pensions' app
 - [x] Create the 'Provider' model and do migrations
 - [x] Test the model
 - [x] Manually test that the admin user can access the table and add records in the admin panel

**Comment by Fiona-T** [comment]
Tasks completed, added test records while logged in as admin, Acceptance criteria met. Closed
