### ISSUE TITLE
USER STORY: Registered user site navigation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#18]
As a **registered user** I can **navigate the site** so that **I can find the page I want to go to**
Depends on #2  and #3 being completed

# Acceptance Criteria
 *  Acceptance Criteria 1:  If a user is not logged in, the header contains the logo (linked to home page) and the links to Sign In and Sign Up
 *  Acceptance Criteria 2: If a user is logged in, the links in the header change: My Jobs, My Pensions, Sign Out are present and Sign Up and Sign In are no longer present.
 *  Acceptance Criteria 3: Header is present on all pages as per above, and fixed to the top of the page
 * Acceptance Criteria 4: Username should be shown when user is logged in

# Tasks
 - [x] Update base.html with the new header links, conditional on user being signed in
 - [x] Check responsiveness of nav bar on smaller screens, with the additional menu items, adjust CSS if necessary
 - [x] Add username to header
 - [x] Test responsiveness (links not tested yet as all pages have not been added at this point)

**Comment by Fiona-T** [comment]
Task completed and acceptance criteria met. Closed.
