### ISSUE TITLE
USER STORY: Understand the benefits of creating an account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#19]
As a **visiting user** I can **find out what I could use the website for if I signed up** so that **I can understand the benefits of signing up and decide whether to sign up**

# Acceptance Criteria
 *  Acceptance Criteria 1:  Home page has a section "What is PensionPal?" explaining briefly what the website will help the user achieve
 *  Acceptance Criteria 2: Home page has a section "Why Use PensionPal?" explaining the benefits to the user
 *  Acceptance Criteria 3: Home page has a section "How to Use PensionPal?" explaining to the user how to get started and how to use the site if they sign up for an account

# Tasks
 - [x] Update the block content in index.html with the three new sections
 - [x] Style the sections (CSS) and ensure responsiveness
 - [x] Test the page responsiveness (view test is part of #2 )

**Comment by Fiona-T** [comment]
Tasks completed, Acceptance Criteria met. Closed.
