### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#2]
As a **visiting user** I can **navigate the site** so that **I can find the page I want to go to**

# Acceptance Criteria
 *  Acceptance Criteria 1:  Header should be at the top of every page
 *  Acceptance Criteria 2: Logo (site name) should be prominent in the header and it links to the home page
 *  Acceptance Criteria 3:  Header contains just Sign Up, Sign In links in addition to the logo (since this is not a registered user)

# Tasks
 - [x] Create the header in base.html template and add CSS for header design (since header will be on every page)
 - [x] Create the index.html template and the view to display it (so header can be viewed on frontend)
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Header created, acceptance criteria fulfilled, initial tests completed. Closing.
