### ISSUE TITLE
USER STORY: Know that no jobs were recorded

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#22]
As a **registered user** I can **see confirmation that I have no jobs recorded ** so that **I know I have not previously recorded any jobs and that is why there are no jobs displayed**

# Acceptance Criteria
 *  Acceptance Criteria 1:  On the My Jobs page there is a note underneath Your Jobs heading confirming that the user does not have any jobs added, if that user has not previously added any jobs, or has added jobs but deleted them
 *  Acceptance Criteria 2: If the user does have jobs in their records, then these are displayed and the note is not displayed

# Tasks
 - [x] Update my-jobs.html template to include a note if the job_list is empty
 - [x] Update the CSS if necessary
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met. Manual testing with user with no jobs and user with jobs. Re-ran test_views.py (no new test added). Closed
