### ISSUE TITLE
USER STORY: Add Job Form - date picker or date format placeholder

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#24]
As a **registered user** I can **easily enter the dates when adding a job** so that **I can complete the form intuitively and easily**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The Add Job form has placeholders/helptext in the Start date and Finish date inputs
 *  Acceptance Criteria 2: The placeholder/helptext shows the format of the date to use 
 *  Acceptance Criteria 3: If possible a date picker is also included on these inputs so that the user can select the date more easily
 
Linked with issue #23 

# Tasks
 - [x] Update the Form with the helptext
 - [x] Investigate if a datepicker can be added to the Form
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Added date format in the input instead of using helptext. Datepicker widget also.

**Comment by Fiona-T** [comment]
Task completed, acceptance criteria met, manual and automated tests done. Closed.
