### ISSUE TITLE
USER STORY: Cancel sign out request

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#25]
As a **registered user** I can **cancel my sign out request** so that **I can easily get back to the page I was previously on**

# Acceptance Criteria
 *  Acceptance Criteria 1:  After clicking the Sign Out button, there is a button saying Cancel, as well as the Sign Out button
 *  Acceptance Criteria 2: Clicking Cancel will bring the user back to the previous page they were on

# Tasks
 - [x] Add the Cancel button to the template
 - [x] Wire up the button to go back to the previous visited page in history
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, script.js added, manual testing done. Closed.
