### ISSUE TITLE
USER STORY: Admin date format

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#26]
As a **site admin** I can **view the date formats in the admin panel as dd/mm/yyyy** so that **the dates are in the format I am used to, living in Ireland**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When the admin user is signed into the admin panel, and views a Job, the dates shown are in the format dd/mm/yyyy and not yyyy/mm/dd
 *  Acceptance Criteria 2: If the admin user goes to the Add Job form in the admin panel and adds start and finish date using the date picker, the date chosen is then displayed in the format dd/mm/yyyy
 *  Acceptance Criteria 3: If the admin user goes to the Add Job form in the admin panel and types in the start and finish date in the format dd/mm/yyyy, the date saves in this same format and does not change into the American format (e.g. 01/05/2021 does not become 5th Jan 2021 

# Tasks
 - [x] Update the language setting in settings.py 
 - [x] Test the dates when viewed in the admin panel and adding a new job
 - [x] Test a job added from the admin panel to ensure dates display correctly on frontend still

**Comment by Fiona-T** [comment]
Adding this issue to Iteration 5 as it is related to the other date format issues #23 and #24

**Comment by Fiona-T** [comment]
Tasks completed (lang code changed from en_us to en_gb, dates format correct, acceptance criteria met. Closed.
