### ISSUE TITLE
USER STORY: Jobs list pagination

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#27]
As a **registered user** I can **view my jobs listings in shorter pages** so that **I can click through each page instead of scrolling through a long list of my jobs**

# Acceptance Criteria
 *  Acceptance Criteria 1:  On the My Jobs page, under Your Jobs, the max number of jobs displayed is 6
 *  Acceptance Criteria 2: If there are more than 6 jobs, then there is a pagination feature at the bottom of the page which allows the user to go from one page to the next/previous
 *  Acceptance Criteria 3: If it is the first page of jobs, then there is only a next arrow. If it is the last page of jobs then there is only a previous arrow

# Tasks
 - [x] Update the View to paginate
 - [x] Update the template to include pagination
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, tests completed. Closed.
