### ISSUE TITLE
USER STORY: Site navigation - know which page user is on

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#29]
As a **user** I can **see which section of the website I am on** so that **I know which part of the website I went into**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The link, in the main navigation in the header, for the page the user is currently on, is styled differently when it is the active page (except for home page as the logo serves as the home page link)
 *  Acceptance Criteria 2: For pages that have 'sub' pages e.g. My Jobs has add job, success page, etc., the different styling remains in the top navigation, when the user is within these sub pages

# Tasks
 - [x] Update base.html template with the conditional logic to add a class depending on the url
 - [x] Update style.css with the style to be applied to the active link
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, manual testing done. Closed.
