### ISSUE TITLE
USER STORY: Sign into account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#3]
As a **registered user** I can **sign into my account** so that **access my jobs and pension information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The page to sign in opens after clicking Sign In from the site header
 *  Acceptance Criteria 2: The sign in page contains the username and password fields to sign in with, and sign in button
 *  Acceptance Criteria 3: After signing in, the user is redirected to the My Jobs page
 * Acceptance Criteria 4: there is a note on the sign in page directing the user to the Sign Up page if they have not previously created an account

# Tasks
 - [x] allauth should already be installed in #6 
 - [x] update base.html with sign in url
 - [x] update settings to ensure the page redirects (will need to create empty My Jobs page for this)
 - [x] style the sign in page template to be in line with the style on the rest of the website
 - [x] test the functionality

**Comment by Fiona-T** [comment]
Tasks completed. Acceptance criteria have been met. Closed.
