### ISSUE TITLE
Issue: Employer name in Jobs form is too long

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#31]
Issue: Need to restrict the Employer Name in the model, it was set too long initially. 

# Acceptance Criteria
 *  Acceptance Criteria 1:  User cannot enter an employer name longer than 40 characters on the Add Job form

# Tasks: 
- [x] Update the employer name field in the Job model and migrate
- [x] Re-run test_models.py in jobs app to ensure all okay
- [x] Test manually from the front end to ensure a longer name cannot be entered

**Comment by Fiona-T** [comment]
Will not be done in Iteration 7, moving back to Product Backlog for re-prioritisation

**Comment by Fiona-T** [comment]
Added to Iteration 8 board in error - this is not scheduled in Iteration 8. Still in product backlog awaiting prioritisation

**Comment by Fiona-T** [comment]
Amended the max_length, made migrations and ran them, re-ran test_models.py file, manually tested, acceptance criteria met. Closed.
