### ISSUE TITLE
USER STORY: Delete a Pension Provider

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#34]
As a **website owner/admin** I can **delete a Pension Provider from the list** so that **they can be removed, if they were added in error**

Edit: This functionality is present by default on the Django admin site, and the admin site is the only place that users interact with the Provider model (there is no frontend for the Provider model as it is intended to be maintained by admin users only). 

However the admin user should not be allowed to delete a pension provider if there are pension records attached to that provider, as this would delete the pension records of the users without their knowledge (the admin user should simply change the status of the provider to inactive)

# Acceptance Criteria
 *  Acceptance Criteria 1:  An admin user in the admin site can delete a Pension Provider, if there are no pension records attached to it
 *  Acceptance Criteria 2: However if there are pension records attached, the deletion is prevented because of the attached pension records

# Tasks
 - [x] Change the pension provider in Pension model to on_delete.PROTECT instead of DELETE
 - [x] Test that this works in the admin site
 - [x] Re-run test_models.py after making the changes

**Comment by Fiona-T** [comment]
Linked to #17  which was originally an Epic: Maintain pension providers list

**Comment by Fiona-T** [comment]
Tasks completed. Tested manually in admin site and re-ran test_models.py. Acceptance criteria met. Closed.
