### ISSUE TITLE
USER STORY: Page not found page consistent with rest of website

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#35]
As a **user** I can **see a custom 'Page not found" page when I try an access a page in error** so that **I can find my way back to the website and I know I have not left the website(as the branding is the same as the rest of the website)**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The 404 page not found displayed to the user is consistent with the branding on the rest of the website
 *  Acceptance Criteria 2:  The page contains the header and footer as per the rest of the webiste
 *  Acceptance Criteria 3: The page contains a note to the user stating the page was not found, and links for them to get back to the website

# Tasks
 - [x] Create the 404 html template and add the content
 - [x] Style the content if needed
 - [x] Test to ensure this page is displayed instead of the generic page (debug must be false to check this)

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, manual testing done. Closed.
