### ISSUE TITLE
USER STORY: Add Pension Confirmation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#36]
As a **registered user** I can **see confirmation that my pension details were added** so that **I know the add Pension form submitted correctly and there were no errors**

# Acceptance Criteria
 *  Acceptance Criteria 1:  After a registered user submits the Add Pension form successfully, they are redirected to a success page
 *  Acceptance Criteria 2: Success page confirms the pension was added and has links to the My Pensions page if they need to edit/delete the pension

# Tasks
 - [x] Create the success page html template
 - [x] Create the view for the success page
 - [x] Style the page - CSS/bootstrap classes
 - [x] Update the add pension view to redirect to this success page after the add pension form is submitted
 - [x] Test the view functionality

**Comment by Fiona-T** [comment]
All tasks completed. Not logged in user is redirected to login page also. Automated and manual testing done. Closed
