### ISSUE TITLE
USER STORY: View details of a Pension

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#37]
As a **registered user** I can **view details of a Pension that I added** so that **I can see all of the details of the pension in full for information or to check that they are correct**

# Acceptance Criteria
 *  Acceptance Criteria 1:  User can click on the View Details button on the pensions list, and this brings up a page showing the full details of that Pension
 *  Acceptance Criteria 2:  All details of the Pension are displayed (except for added by), along with date of joining service, date of leaving service (from the related Job), and pension provider website (from the related Provider)
 *  Acceptance Criteria 3: There are two buttons at the bottom of the page, one to Edit and one to Delete

# Tasks
 - [x] Create the view-pension html template
 - [x] Create the view to display the template and data
 - [x] Update urls.py with the url pattern
 - [x] Update the link on my-pensions cards with the new view-details url
 - [x] Update CSS as needed (style.css / Bootstrap classes)
 - [x] Test the view

**Comment by Fiona-T** [comment]
All tasks completed. Automated testing completed. Closed.
