### ISSUE TITLE
Issue: Pagination navigation not present on My Pensions page

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#38]
Issue: The pensions are shown max 6 per page but the navigation to move through the pages is missing.

# Acceptance Criteria
 *  Acceptance Criteria 1:  On the My Pensions page, under Your Pensions, the max number of pensions displayed is 6
 *  Acceptance Criteria 2: If there are more than 6 pensions, then there is a pagination feature at the bottom of the page which allows the user to go from one page to the next/previous
 *  Acceptance Criteria 3: If it is the first page of pensions, then there is only a next arrow. If it is the last page of pensions then there is only a previous arrow

# Tasks: 
- [x] Update the template to include pagination navigation
- [x] View already includes pagination - check
- [x] Test the functionality

**Comment by Fiona-T** [comment]
Tasks completed, acceptance criteria met, re-ran test_views.py and tested manually. Closed.
