### ISSUE TITLE
USER STORY: Sign out of account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#4]
As a **registered user** I can **sign out of my account when finished** so that **I know I am signed out securely**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is signed in, the Sign Out link is present in the header
 *  Acceptance Criteria 2: After clicking the Sign Out link, the Sign Out page opens
 *  Acceptance Criteria 3: Sign Out page has text asking user to confirm they want to sign out, and a button
 * Acceptance Criteria 4: after signing out, the user is redirected to the home page and the header reflects the status of a user who is not logged in, i.e. only contains the Sign In and Sign Up links and not My Jobs/My Pensions/Sign Out

# Tasks
 - [x] base.html should already be updated in #18 to show the sign out link in the header
 - [x] update the settings with the sign out redirect url
 - [x] update the allauth template  to have the same style as the rest of the website
 - [x] test the functionality - manual testing to ensure links function and acceptance criteria are met

**Comment by Fiona-T** [comment]
All tasks completed. Acceptance criteria are met. Closed.
