### ISSUE TITLE
USER STORY: Add Pension - notification if user does not have any Jobs recorded

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#40]
As a **registered user** I can **be notified that I have no recorded Jobs when I try to Add a Pension** so that **I can then add the Job, since the Job needs to be added before the Pension can be added**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When the user does not have any Jobs recorded and clicks on the Add Pension button, the Add Pension form is not displayed (as they cannot add a pension without linking it to one of their job records)
 *  Acceptance Criteria 2: Instead they are shown a notification that they do not have any jobs recorded yet
 *  Acceptance Criteria 3: The notification reminds them that they need to add the job/employment first before they can add the pension, and provides the link to the add job form/ my-jobs page

# Tasks
 - [x] Update the AddPension View logic to check if the user has any jobs recorded, and display notification if they don't
 - [x] Create the html to display the notification
 - [x] Update the tests for AddPension view to test the new logic

**Comment by Fiona-T** [comment]
Tasks completed. Manual and automated testing done. Closed.
