### ISSUE TITLE
USER STORY: Can't add Job with same Employment name

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#42]
As a **registered user** I can **not add a new Employment with the same name as another Employment in my Jobs records** so that **I don't add duplicate records which would cause confusion**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A logged in user on the Add Job form, cannot add an Employer Name that matches the employer name of one of their existing Job records
 *  Acceptance Criteria 2: If they try to do this, an error is displayed on the Add Job form explaining that the employer name already exists and to edit or delete the existing Job record, or add a different Employer name for the new record
 *  Acceptance Criteria 3: The Add Job form cannot be submitted until the Employer name differs to any of that user's existing job records

# Tasks
 - [x] Update the job model to include a constraint so that employer name must be unique for that user
 - [x] Migrate the changes
 - [x] Update the tests for the model
 - [x] Test manually
 - [x] Views.py needs to be updated also for AddJob and EditJob views, to 1) set added_by before calling is_valid on the form (as this is needed for unique constraint, employer name by added_by, and 2) return the original form if the form is not valid, instead of returning a new instance of the form
 - [x] test_views needs to be updated for the new functionality
 - [x] forms.py needs to be updated to include a more helpful error message
 - [x] ~~test_forms.py needs to be updated for the new functionality~~ not done as the validation is done on the model,  model tests have been updated

**Comment by Fiona-T** [comment]
Added new tasks to reflect the actual work needed which only came to light while developing this feature
