### ISSUE TITLE
USER STORY: Delete Job confirmation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#43]
As a **registered user** I can **see confirmation a Job record was deleted after I press Delete button** so that **I know the record was definitely deleted**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A logged in user, after pressing the Delete button and then the Delete Job button on the Delete Job modal, is returned to the My Jobs page (existing functionality) A message is displayed on the My Jobs page confirming the Job record was deleted

# Tasks
 - [x] update settings.py to import messages and assign tags
 - [x] update base.html to display the messages
 - [x] create script to dismiss the alerts
 - [x] update the view to display a message
 - [x] test manually
 - [x] update the test_views to test the new functionality

**Comment by Fiona-T** [comment]
Tasks completed, manual and automated testing done, acceptance criteria met. Closed.
