### ISSUE TITLE
USER STORY: Delete pension confirmation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#44]
As a **registered user** I can **see confirmation that a Pension record was deleted, after I press the Delete button** so that **I know the record was definitely deleted**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A logged in user, after pressing the Delete button and then the Delete Pension button on the Delete Pension modal, is returned to the My Pensions page (existing functionality) A message is then displayed on the My Pensions page confirming the Pension record was deleted 

# Tasks
 - [x] settings.py and base.html should already be updated (as well as script) in #43 
 - [x] update the view to display a message
 - [x] test manually
 - [x] update test_views to test the new functionality

**Comment by Fiona-T** [comment]
Tasks completed, manual and automated tests completed. Acceptance criteria met. Closed.
