### ISSUE TITLE
USER STORY: Edit Pension record confirmation

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#46]
As a **registered user** I can **see confirmation that the edits I made to my pension record were successful,** so that **I know the changes made have been saved**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A logged in user, after pressing the Confirm Changes button on the Edit Pension form is returned to the My Pensions page if the form was submitted successfully (existing functionality). A message is then displayed on the My Pensions page confirming the Pension record was successfully updated with the changes

# Tasks
 - [x] settings.py and base.html should already be updated (as well as script) in #43 
 - [x] update the view to display a message
 - [x] test manually
 - [x] update test_views to test the new functionality

**Comment by Fiona-T** [comment]
Tasks completed, manual and automated testing done. Acceptance criteria met. Closed.
