### ISSUE TITLE
USER STORY: Pension form mandatory fields

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#47]
As a **registered user** I can **see which fields on the Add/Edit Pension form are mandatory** so that **I understand which fields must be completed by me and which are optional**

# Acceptance Criteria
 *  Acceptance Criteria 1:  On the Add Pension and Edit Pension pages, there is a note explaining which fields are mandatory and some identifying feature on the fields (e.g. asterisk)
 *  Acceptance Criteria 2:  The form can be submitted if the optional fields are left blank

# Tasks
 - [x] Update the add-pension and edit-pension html templates to include a note re the mandatory/optional fields
 - [x] Test manually to confirm that the fields are mandatory/optional, and can submit with the optional fields blank
 - [x] Check test_forms to ensure there is a test for mandatory/optional fields

**Comment by Fiona-T** [comment]
Tasks completed. Updated forms.py with required_css_class so class is added to label (so could use ::after in the css to add an asterisk, as did not work using ::before on the required input). Re-ran test_forms.py - it already includes test on mandatory fields. Manual testing done also. Acceptance criteria met. Closed.
