### ISSUE TITLE
USER STORY: Access Edit Job page from View Pension or Edit Pension pages

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#53]
As a **registered user** I can **click a link that brings me to the Edit Job page, from the View or Edit pages of the attached Pension** so that **I can go directly to the Edit page of the associated Job, instead of having to navigate to it**

# Acceptance Criteria
 *  Acceptance Criteria 1:  There is a link directly to the Edit Job page from the View Full Details page for a pension
 *  Acceptance Criteria 2: There is a link directly to the Edit Job page from the Edit Pension page
 *  Acceptance Criteria 3: The linked Edit Job page is to edit the job that the pension is attached to 

# Tasks
 - [x] Edit the EditPension and PensionDetails views in views.py, to pass the relevant job back as part of the context
 - [x] Update the edit-pension.html and view-pension.html pages to include the edit job url, with job id
 - [x] Test manually
 - [x] Re-run the test_views.py in pensions and jobs app to ensure the tests still pass.

**Comment by Fiona-T** [comment]
All tasks completed, acceptance criteria met. Tested manually and re-ran test_views.py. Closed.
