### ISSUE TITLE
USER STORY: Easily View Pension Details after adding a new pension

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#54]
As a **registered user** I can **easily view the full details of the pension I just added by clicking a link from the add pension success page** so that **I can check that I added all the details correctly**

# Acceptance Criteria
 *  Acceptance Criteria 1:  After submitting the Add Pension form, the success page contains a link to view the full details of the pension just added 
 *  Acceptance Criteria 2: The link brings the user to the Pension Details page where they can see all details of that pension, and the associated job 
 *  Acceptance Criteria 3: The success page still contains a link to the My Pensions page, so the user can go here if they don't want to go to the Pension Details page

# Tasks
 - [x] Update AddPension view to include the pension  in the context when rendering the success page
 - [x] Update the add-pension-success html template to include a url link to the view_pension url
 - [x]  Update AddPensionSuccess view to have a get request, use the pension id, and check the pension id belongs to user, else display 404
 - [x] Test manually
 - [x] re-run test_views.py, and update it with test on AddPensionSuccess view to ensure only that user can view the page

**Comment by Fiona-T** [comment]
Tasks completed, additional tasks were added to update the AddPensionSuccess view, and to add new tests for this view. Acceptance criteria met. Manual and automated testing done. Closed.
