### ISSUE TITLE
USER STORY: Job form displays error if finish date entered is before the start date

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#55]
As a **registered user** I can **see a relevant error message if I enter a job finish date that is before the start date** so that **I can correct the error before the job record is saved**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When adding or editing a job, if the user enters a finish date that is before the start date on the form, the job is not added
 *  Acceptance Criteria 2: The form is displayed again to the user, with an error message stating what the issue is, along with the data they previously entered into the form
 *  Acceptance Criteria 3: When the user corrects the error and submits the form, the job is added/edited successfully

# Tasks
 - [x] Update the AddJob form to include a check on the start date and finish date fields and raise error msg
 - [x] Test manually
 - [x] Update test_forms.py in jobs app to include a test on the new functionality
 - [x] Update style.css with styles for the error message, if needed. Done as part of #42

**Comment by Fiona-T** [comment]
Tasks completed, manual and automated testing done. Acceptance criteria met. Closed.
