### ISSUE TITLE
USER STORY: Pension form - allowed file types

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#56]
As a **registered user** I can **know what file types I can upload when adding/editing a pension** so that **I can avoid uploading a file type that is not allowed**

# Acceptance Criteria
 *  Acceptance Criteria 1:  On the Add Pension or Edit Pension forms, there is a note on the file field advising what file types can be uploaded
 *  Acceptance Criteria 2: If the user adds a file that is not one of the allowed file types, an error is displayed on the form when trying to submit the form
 *  Acceptance Criteria 3: The allowed file types are jpg and png

# Tasks
 - [x] update the helptext in forms. py for the 'file' field on the PensionForm to include a note on file types
 - [x] add a clean method in forms.py to check the file type on that field and raise and error message
 - [x] Test manually
 - [x] Update test_forms.py to include test that error message is raised

**Comment by Fiona-T** [comment]
All tasks completed. Acceptance criteria met. Manual testing completed. New automated tests done. Closed
