### ISSUE TITLE
USER STORY: Only show active Pension Providers when adding/editing a pension record

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#59]
As a **registered user** I can **choose from a list of only the active Pension Providers on the pension provider field when adding  or editing a pension** so that **I know that the pension provider is a current one**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is adding a pension record, the 'Pension provider' dropdown list only contains the Pension Providers that have a status of active
 *  Acceptance Criteria 2:  When a user is editing a pension record, the 'Pension provider' dropdown list only contains the Pension Providers that have a status of active

# Tasks
 - [x] Update the pension provider queryset in the form to filter by the active status
 - [x] Test manually to ensure only active providers are in the list
 - [x] Update test_forms.py to take account of new functionality

**Comment by Fiona-T** [comment]
Tasks completed, manual and automated tests done. Acceptance criteria met. Closed
