### ISSUE TITLE
USER STORY: Sign up/create account

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#6]
As a ** new user** I can ** sign up for an account** so that **I can start recording my jobs and pensions details**

# Acceptance Criteria
 *  Acceptance Criteria 1:  The sign up page opens after clicking the Sign Up link in the header
 *  Acceptance Criteria 2: Sign up page contains contains fields for the user to register with a username, email address and password and a button to submit the form
 *  Acceptance Criteria 3: After submitting the form the user is brought to the My Jobs page (as they are now signed in)
 * Acceptance Criteria 4: The user can't submit the form unless all the fields have been completed

# Tasks
 - [x] Install allauth and set up urls, run migrations
 - [x] Update base.html with the sign up url
 - [x] Update settings to ensure page redirects. This can't be done until #3 is done
 - [x] amend the sign up page template to extend the project base.html and make any style changes so that it matches the style on the rest of the website
 - [x] Test the functionality

**Comment by Fiona-T** [comment]
Not completed in Iteration 2  (Could-Have contingency). Moved back to Product Backlog to be re-prioritised for next Iteration

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met. Closed.
