### ISSUE TITLE
USER STORY: Add a job

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#7]
As a ** registered user** I can **record details of a job** so that **I can build up my employment history records**

# Acceptance Criteria
 *  Acceptance Criteria 1:  A registered user can go to the My Jobs page, click Add a Job and a form is displayed for them to complete
 *  Acceptance Criteria 2: The form contains fields for Employer name, date of joining, date of leaving, and whether the employment was full or part time.
 *  Acceptance Criteria 3: All fields on the form are mandatory
 * Acceptance Criteria 4: After adding the employment details, the user can see these details in the My Jobs page

# Tasks
 - [x] Create the jobs app
 - [x] Create the Job model and do migrations
 - [x] Update the project urls file with the path for the jobs app urls
 - [x] Add url to jobs app url file (and remove temporary one from pages app url file)
 - [x] Update my-jobs.html template to include the two sections (Add Job and Your Jobs), and the Add Job button
 - [x] Move the MyJobs view that was temporarily created in pages app to the jobs app views file
 - [x] Create the add-job.html template and add url to jobs urls file
 - [x] Create the add job form
 - [x] Create the view for displaying the add job form
 - [x] Create the view for posting the completed add job form
 - [x] Style the new pages (CSS)
 - [x] Test the views (my jobs and add job)
 - [x] Test the add-job form
 - [x] Test the Job model

**Comment by Fiona-T** [comment]
All tasks completed, acceptance criteria met, closed.
