### ISSUE TITLE
USER STORY: View jobs

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#8]
As a **registered user** I can **see all the jobs I have added** so that **I can get the overall picture of my work history**

# Acceptance Criteria
 *  Acceptance Criteria 1:  When a user is logged in and on the My Jobs page, all jobs added by that user are listed here
 *  Acceptance Criteria 2: The jobs added to date are shown in a section called Your Jobs
 *  Acceptance Criteria 3: Each job has the Employer name (prominently), the start and end date, and whether it was full or part time

# Tasks
 - [x] Update the my-jobs.html template to display the jobs and their details
 - [x] Update the MyJobs view to display the relevant details from the database
 - [x] Add CSS to style the view
 - [x] Test the view

**Comment by Fiona-T** [comment]
Tasks completed, tests completed, acceptance criteria met. Closed.
