### ISSUE TITLE
USER STORY: Edit job details

### ISSUE THREAD

**Issue by Fiona-T** [Fiona-T/pension-pal#9]
As a **registered user** I can **edit a job** so that **I can correct the previously recorded information**

# Acceptance Criteria
 *  Acceptance Criteria 1:  User can click on the Edit button on the jobs list, and this brings up a form to edit the details
 *  Acceptance Criteria 2: The existing details of the job are pre-populated on the form so user just needs to update the fields that are changing
 *  Acceptance Criteria 3: The form contains the same fields as the Add Job form, along with a confirmation button to Confirm, or a cancel button to go back
 *  Acceptance Criteria 4: After submitting the form, the user is redirected to the my jobs page
 *  Acceptance Criteria 5: The job in the jobs list now shows the amended details

# Tasks
 - [x] create the template, create the view logic
 - [x] add url to urls.py file in jobs app, and update links on my-jobs page Edit button
 - [x] update styles in style.css if needed
 - [x] test the functionality

**Comment by Fiona-T** [comment]
Tasks completed and acceptance criteria met, manual and automated tests done. Closed.
